apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-pod
        image: worker_img

        imagePullPolicy: IfNotPresent
        args:
        - bash
        - /root/worker.sh
        ports:
        - containerPort: 7077

